alertmanager:
  enabled: false
pushgateway:
  enabled: false
server:
  name: prometheus-deployment
  service:
    type: LoadBalancer

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090
      - job_name: webapp
        static_configs:
          - targets:
            - webapp-service:8080